# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e023fea22b847c3c851648de9a5127145d13deef22e013b90d7bc0cf80a4731de302bd21ecba894b57b338885bc48a8bd9dcde3a0417196322b85da6816bbb47

test:
  secret_key_base: 045475fa432cab67de475587924fc8fc1d30dfe993c87328afff779c3689c3cb025a279f20148b2b6cc3ccfe25c5a4e7d9fda5b59b0fc5aaf66727541d275262

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
